version: '3'

tasks:
  setup:
    desc: Install all dependencies
    cmds:
      - python3 -m venv venv
      - venv/bin/pip install -r requirements.txt

  train:
    desc: Fine-tune the model (reads configs/train_config.yaml)
    cmds:
      - venv/bin/python src/train.py

  evaluate:
    desc: Evaluate fine-tuned model and output JSON results
    cmds:
      - venv/bin/python src/evaluate.py

  app:
    desc: Launch Gradio GUI locally
    cmds:
      - venv/bin/python src/app.py

  chat:
    desc: Interactive CLI chat
    cmds:
      - venv/bin/python src/inference.py

  lint:
    desc: Lint source code
    cmds:
      - venv/bin/ruff check src/ --select E,W,F --ignore E501

  deploy-model:
    desc: Upload adapter weights to HF Hub
    cmds:
      - venv/bin/python .github/scripts/deploy_to_hf.py --mode model

  deploy-space:
    desc: Sync app to HF Spaces
    cmds:
      - venv/bin/python .github/scripts/deploy_to_hf.py --mode space

  deploy:
    desc: Upload model + sync Space
    cmds:
      - venv/bin/python .github/scripts/deploy_to_hf.py --mode all

  sync-secrets:
    desc: Push .env secrets to GitHub Actions
    cmds:
      - bash .github/scripts/sync_secrets.sh
